name: Cache node and PNPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the pnpm-lock.yaml file."

inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: 20.x
  working-dir:
    description: "The working directory of the application"
    required: false
    default: "."
runs:
  using: "composite" #inform gh-actions that this is composite custom action
  steps: #execution array
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Calculate cache key
      id: cache-key
      run: |
        echo "CACHE_KEY=deps-node-modules-${{ runner.os }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.working-dir)) }}" >> $GITHUB_OUTPUT

    - name: Download cached dependencies
      id: cache
      uses: actions/cache@v3
      with:
        # ✅ added caching of store
        path: |
          ~/.pnpm-store                            
          ${{inputs.working-dir}}/node_modules
        key: ${{steps.cache-key.outputs.CACHE_KEY}}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{inputs.working-dir}}
      shell: bash
      run: |
        pnpm config set store-dir ~/.pnpm-store 
        echo 'Installing new dependencies'
        pnpm install
