name: 02-temp-workflow-events

on:
  - push
  - pull_request
  - workflow_dispatch
  - schedule

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Triggered by ${{github.event_name}}"
