name: 05 - 2 - Event Filters and Activity Types
on:
  pull_request:
    types:
      - closed
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print whenever PR is opened or Sync
        run: echo "Triggered by ${{github.event_name}} AND base branch is main"
