name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:
    inputs:
      shouldFail:
        type: number
        default: 1

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Details
        run: |
          echo "Title ${{github.event.pull_request.title}}"
          cat << EOF
          "Labels ${{ toJson(github.event.pull_request.labels)}}"
          EOF
      - name: "[🪲] Bug Step"
        if: ${{failure() && !cancelled() && contains(github.event.pull_request.title, 'fix')}}
        run: echo I am a bug fix f⚒️
      - name: Sleep for 20 secs
        run: sleep 20
      - name: Failing step
        run: exit ${{inputs.shouldFail}}
      - name: Execute if prev succeded
        if: ${{success()}}
        run: echo "I will print if ancestor succeeds"
      - name: Execute if any prev is failed
        if: ${{failure()}}
        run: echo "I will execute if ancestor fails"
      - name: Execute if not cancelled
        if: ${{!cancelled()}}
        run: echo "I will execute if workflow is not cancelled"
      - name: Execute when cancelled
        if: ${{cancelled()}}
        run: echo "I am running because of cancellation"
