name: 14 - Artifacts

on:
  workflow_dispatch:

env:
  build-artifact-key: app-${{github.sha}}
  test-coverage-key: test-coverage-${{github.sha}}

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{hashFiles('04-using-actions/react-app/pnpm-lock.yaml')}}
          path: 04-using-actions/react-app/node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Test coverage report
        run: pnpm coverage

      - name: Upload test resutls
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.test-coverage-key}}
          path: 04-using-actions/react-app/coverage

      - name: Building
        run: pnpm build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.build-artifact-key}}
          path: 04-using-actions/react-app/dist
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: ${{env.build-artifact-key}}
          path: dist
      - name: Show folder structure
        run: ls -R
