name: 15 - Working with matrices

on:
  workflow_dispatch:
    inputs:
      fail-fast:
        description: Strategy fail fast
        type: boolean
        default: false

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{inputs.fail-fast}}
      matrix:
        node: [20.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            node: 21.x
            experimental: true

    name: "${{matrix.os}}-${{matrix.node}}"
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: Fail if experimental
        if: ${{matrix.experimental}}
        run: |
          echo "Failing due to experimental"
          exit 1
      - name: Perform some tests
        run: |
          echo "Testing on OS ${{matrix.os}} and NodeJS ${{matrix.node}}"
          sleep 10
      - name: Upload test results
        run: |
          echo "Uploading test results"
  include-example:
    runs-on: ubuntu-latest
    name: ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}} - ${{matrix.opacity}}
    strategy:
      matrix:
        color: [red, green]
        shape: [circle, suquare]
        size: [small, large]
        include:
          - opacity: 50
          - color: red
            shape: triangle
    steps:
      - name: Dummy step
        run: echo ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}}
