name: 16 - working with Environments
run-name: 16 - Working with Envs | env - ${{github.env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
      my-env-value: ${{vars.MY_ENV_VALUE || 'default env value'}}
    steps:
      - name: Echo vars
        run: echo "Env variable ${{vars.MY_ENV_VALUE}}"
