name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 04-using-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: "./.github/actions/composite-cache-deps"
        with:
          node-version: 20.x
          working-dir: ${{env.working-directory}}
          target-env: prod
      - name: Testing
        run: pnpm test

      - name: Build
        run: pnpm build
