name: On PR Closed and main branch

on:
  pull_request:
    types: [closed]
    branches: main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: run on pr closed and main branch
        run: echo "run on pr closed and main branch"
