name: 09 - temp - using functions

on:
  pull_request:
  workflow_dispatch:
    inputs:
      exit_code:
        type: number
        default: 1

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo ${{github.event.pull_request.title}}
      - name: Print PR labels
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF
      - name: BUG STEP
        if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
        run: echo ${{github.event.pull_request.title}}
      - name: Failing step
        run: exit ${{inputs.exit_code}}
      - name: I will be skipped
        if: ${{success()}}
        run: echo "I will print if prev step succeeded"
      - name: I will execute if prev failed
        if: ${{failure()}}
        run: echo "I will print if prev fails"
      - name: I will execute
        if: ${{!cancelled()}}
        run: echo "I will print except if cancelled"
      - name: I will exec when cancelled
        if: ${{cancelled()}}
        run: echo "Executed because of cancellation"
